README.md
=> 1 update readme

Orbitersdk/CMakeLists.txt, Src/Vessel/DeltaGlider/CMakeLists.txt, Src/Vessel/ShuttleA/CMakeLists.txt
=> #4 applied patch

CMakeLists.txt
=> #45: updated the 64-bit build check

Orbitersdk/include/GraphicsAPI.h, Src/Orbiter/elevmgr.cpp
=> Face elevmgr

Orbitersdk/CMakeLists.txt
=> #56: fixed cmake script for Orbitersdk/lib install

CMakeLists.txt, Orbitersdk/CMakeLists.txt
=> 58 diable documentation build

Src/Orbiter/Config.cpp
=> #77 Disable font smoothing default set to false.

Src/Plugin/ScnEditor/CMakeLists.txt
Deployed in Orbiter builds and installs.
closes #79
=> deploy Src/Plugin/ScnEditor/ScnEditorAPI.h to Orbitersk/include

CMakeLists.txt, Html/CMakeLists.txt, Html/Scenarios/CMakeLists.txt
=> #81: the CurrentState Html templates are now always deployed.

Src/Vessel/DeltaGlider/CMakeLists.txt
=> #76: DeltaGlider.rc added to DeltaGlider target sources.

Src/Orbiter/TabVideo.cpp
Info text for built-in graphics updated.
closes #113
=> #113: client info button registered for alignment.

Sound/XRSound/XRSound/assets/XRSound/ReadMe.txt, Sound/XRSound/XRSound/src/XRSoundDLL/XRSoundDLL.cpp, Sound/XRSound/XRSound/src/XRSoundDLL/XRSoundDLL.vcxproj, Sound/XRSound/XRSound/src/XRSoundDLL/XRSoundDLL.vcxproj.filters, Sound/XRSound/XRSound/src/XRSoundDLL/XRSoundEngine.cpp, Sound/XRSound/XRSound/src/XRSoundDLL/XRSoundEngine.h, Sound/XRSound/XRSound/src/XRSoundDLL/XRSoundEngine10.h, Sound/XRSound/XRSound/src/XRSoundDLL/XRSoundEngine20.h, Sound/XRSound/XRSound/src/XRSoundDLL/XRSoundEngine30.cpp, Sound/XRSound/XRSound/src/XRSoundDLL/XRSoundEngine30.h, Sound/XRSound/XRSound/src/XRSoundLib/XRSound.cpp, Sound/XRSound/XRSound/src/XRSoundLib/XRSound.h, Sound/XRSound/XRSound/src/XRSoundLib/XRSoundImpl.cpp, Sound/XRSound/XRSound/src/XRSoundLib/XRSoundImpl.h, Sound/XRSound/XRSound/src/XRSoundLib/XRSoundLib.vcxproj
* Added SetPan, GetPan, SetPlaybackSpeed, GetPlaybackSpeed, SetPlayPosition, GetPlayPosition functions for XRSound 3.0
* Fixed some post-build event copy commands.
* Fixed the copyright year in a few files.
* Cleaned up the code in a few places.
=> XRSound: implemented six more sound manipulation methods for XRSound 3.0

.github/workflows/artifact-cleanup.yml, .github/workflows/build.yml
* retain last 4 artifacts - 2x 64-bit+2x 32-bit
* increase artifact retention to 60 days
* cleanup at 1AM GMT every day
* cleanup will be automatically stopped by GitHub if no activity in repo for 60 days
=> Adding x86 artifact + artifact cleanup

Script/Tests/VesselApiTest.lua
Brings test time down to 5s from 30s
=> Added time acceleration to VesselApiTest

OVP/D3D9Client/D3D9Pad.h, OVP/D3D9Client/Scene.cpp, OVP/D3D9Client/VVessel.cpp, Sound/XRSound/XRSound/src/XRSoundDLL/DefaultSoundGroupPreSteps.cpp, Src/Orbiter/MfdSync.cpp, Src/Plugin/TransX/basefunction.cpp, Src/Plugin/TransX/planfunction.cpp, Src/Plugin/TransX/transx.cpp, Src/Plugin/TransX/transxstate.cpp, Src/Vessel/Common/Instrument.cpp, Src/Vessel/DeltaGlider/DeltaGlider.cpp, Src/Vessel/DeltaGlider/ThermalSubsys.cpp
* Fixed D3D9Client crash removing objects
* Removed XRSound ASSERT that can be triggered on long sessions
* Fixed  TransX crashes
* Better TransX message text
* Added initial variable assignments
* Fixed DeltaGlider crashes due BOF
=> Multiple fixes on D3D9Client branch

OVP/D3D9Client/VVessel.cpp, Sound/XRSound/XRSound/src/XRSoundDLL/VesselXRSoundEngine.cpp, Src/Orbiter/Pane.cpp, Src/Orbiter/State.cpp, Src/Orbiter/ddeserver.cpp, Src/Orbiter/elevmgr.h, Src/Plugin/TransX/TransXFunction.cpp, Src/Plugin/TransX/basefunction.cpp, Src/Plugin/TransX/globals.cpp, Src/Plugin/TransX/mfdvarhandler.cpp, Src/Plugin/TransX/mfdvariable.cpp, Src/Plugin/TransX/mfdvartypes.cpp, Src/Plugin/TransX/planfunction.cpp, Src/Plugin/TransX/transxstate.cpp, Src/Vessel/DeltaGlider/DockingSubsys.cpp, Src/Vessel/DeltaGlider/MomentInd.cpp
- Add Pane.cpp fix for #157
- VVessel.cpp force Mu symbol ASCII code
- Buffer init
- Fix 64bit related compiler warnings
=> Multiple fixes

Src/Orbiter/Camera.cpp, Src/Orbiter/Mfd.cpp, Src/Orbiter/MfdSurface.cpp, Src/Orbiter/Orbiter.cpp, Src/Orbiter/Vessel.cpp, Src/Orbiter/elevmgr.h
- Fix camera missing default case and a copy & paste error
- MFD sanity checks to avoid DBZ and BoF
- Minor fixes on Orbiter.cpp
- Fix race condition on Vessel.cpp
- Added initial values
=> Multiple bugfixes

Src/Orbiter/Mfd.cpp, Src/Orbiter/MfdSurface.cpp, Src/Orbiter/Vessel.cpp
- Fix crash on MFD
- Init values
=> Fix crash on MFD

OVP/D3D7Client/Camera.cpp, OVP/D3D7Client/D3D7Client.cpp, OVP/D3D7Client/spherepatch.cpp, OVP/D3D9Client/D3D9Effect.cpp, Src/Orbiter/Config.cpp, Src/Orbiter/MfdSurface.cpp, Src/Orbiter/OGraphics.cpp, Src/Orbiter/OGraphics.h, Src/Orbiter/Panel2D.cpp, Src/Orbiter/Psys.cpp, Src/Orbiter/Scene.cpp, Src/Orbiter/Spherepatch.cpp, Src/Orbiter/SuperVessel.cpp, Src/Orbiter/VBase.cpp, Src/Orbiter/VectorMap.cpp, Src/Orbiter/Vessel.cpp, Src/Orbiter/Vesselbase.cpp, Src/Orbiter/Vvessel.cpp, Src/Orbiter/ddeserver.cpp, Src/Orbiter/resource.h, Src/Vessel/DeltaGlider/Horizon.cpp, Src/Vessel/DeltaGlider/InstrAoa.cpp
- Fix 32 bit warnings
- Fix double definition of IDD_PAGE_DEV on resource.h
=> Fix 32 bit warnings

CMakeLists.txt, Orbitersdk/include/afxres.h, Src/Module/LuaScript/LuaInterpreter/Interpreter.cpp, Src/Orbiter_ng/afxres.h, Src/Plugin/LuaConsole/ConsoleInterpreter.cpp, Src/Plugin/LuaMFD/MfdInterpreter.cpp, Utils/Date/CMakeLists.txt, Utils/Shipedit/CMakeLists.txt
Include afxres.h
Add MFC detection and skip building Date and Shipedit utils when missing.
=> Fixes for building with community edition of VS (no MFC)

OVP/D3D9Client/Scene.cpp, Src/Orbiter/DlgCamera.cpp
Apply fix #179
Remove button highlighting to address #180
=> Fix #179 and #180

Src/Orbiter/Orbiter.cpp, Src/Orbiter/State.cpp, Src/Orbiter/State.h, Src/Plugin/ScnEditor/Editor.cpp, Src/Plugin/ScnEditor/ScnEditor.rc
Scenario editor save page now offers choice between default "Current state" page and custom description.
Closes #192
=> #192: Scenario editor: fix missing description on save

Src/Plugin/Framerate/Framerate.cpp
Converted Framerate plugin to Module interface (singleton implementation)
Closes #217
=> Framerate plugin interface updated

Src/Orbiter/Orbiter.cpp, Src/Plugin/Framerate/Framerate.cpp, Src/Plugin/Rcontrol/Rcontrol.cpp
=> Cleaned up RControl plugin interface.

Src/Orbiter/Log.cpp, Src/Orbiter/Log.h, Src/Plugin/Common/Dialog/Graph.cpp, Src/Plugin/Common/Dialog/Graph.h, Src/Plugin/FlightData/FDGraph.cpp, Src/Plugin/FlightData/FDGraph.h, Src/Plugin/FlightData/FlightData.cpp, Src/Plugin/FlightData/FlightData.rc, Src/Plugin/FlightData/resource.h, Src/Plugin/Framerate/Framerate.cpp, Src/Plugin/Rcontrol/Rcontrol.cpp
- FlightData plugin has been updated to use oapi::Module interface.
- Code refactoring and cleanup of FlightData module.
Closes #221
=> 221 flightdata module interface

Src/Vessel/DeltaGlider/DeltaGlider.cpp
Corrected position of DG RCS exhausts to match the mesh.
=> DG RCS exhaust

.github/workflows/build.yml, cmake/FindDXSDK.cmake
added DXSDK_DIR location to cmake configure command line in build.yml
=> cmake configure DXSDK location in build.yml to build D3D9Client

Scenarios/Delta-glider/Venus takeoff.scn, Scenarios/Demo/Description.txt, Scenarios/Demo/Project Alpha.scn, Scenarios/Dragonfly/Dragonfly021118.scn, Scenarios/Navigation/Lunar transfer/Lunar transfer 1.scn, Scenarios/Navigation/Special orbits/Geostationary orbit.scn, Scenarios/Navigation/Special orbits/Molniya orbit.scn, Scenarios/Navigation/Special orbits/Tundra orbit.scn, Scenarios/Navigation/TransX/01 Ready to Launch.scn, Scenarios/Navigation/TransX/04 plan removed.scn, Scenarios/Navigation/TransX/09 Jupiter sling.scn, Scenarios/Shuttle-A/Shuttle-A Moon.scn, Scenarios/Space Shuttle Atlantis/Atlantis ISS Resupply.scn, Scenarios/Space Stations/Blue Danube.scn, Scenarios/Space Stations/ISS.scn, Scenarios/The Solar System/Eclipses/April 8 2005.scn, Scenarios/Tutorials/ADI training.scn, Scenarios/Tutorials/Smack! Rescue.scn
=> Fixed typos in .scn files #236

Tests/CMakeLists.txt
=> #264: disabled tests relying on Orbiter server version if it was not built.

.github/workflows/build.yml
#295: experimental: added automatic pre-release generation to build workflow.
=> WIP: auto-generate pre-releases on PR to main

Src/Orbiter/Base.h, Src/Orbiter/Baseobj.cpp, Src/Orbiter/CMakeLists.txt, Src/Orbiter/DlgInfo.cpp, Src/Orbiter/OptionsPages.cpp, Src/Orbiter/Orbiter.cpp, Src/Orbiter/Orbiter.h, Src/Orbiter/Psys.cpp, Src/Orbiter/Psys.h, Src/Orbiter/Scene.cpp, Src/Orbiter/Star.cpp, Src/Orbiter/Star.h, Src/Orbiter/TimeData.cpp, Src/Orbiter/TimeData.h, Src/Orbiter/VBase.cpp, Src/Orbiter/Vessel.h, Src/Orbiter/Vobject.h, Src/Orbiter/Vvessel.cpp
- Replaces manually managed collections in `PlanetarySystem` (Vessels, Bodies, Celestials etc.) with std::vector and fixes singular/plural confusion with some of the member names.
I'm not a strong defender of 'Everything should use STL' but some of the re-/de-/allocation code was really verbose and hard to understand without any real advantage to a simple std::vector. It is not the first use of std::vector in the project so I assumed, it would be fine.
- Removes Orbiter.h as a dependency from `PlanetarySystem`.
`PlanetarySystem` is at the 'Base' of the simulation with higher level systems built on top of it. E.g. the render modules for...well...rendering or the Launchpad for Scenario selection, settings etc.
Having Orbiter.h (and therefore other dependencies like the Launchpad and a lot …
=> PlanetarySystem cleanup/refactor

Src/Celbody/Vsop87/Earth/Atmosphere/EarthAtmNRLMSISE00/nrlmsise-00.c, Src/Celbody/Vsop87/Earth/Atmosphere/EarthAtmNRLMSISE00/nrlmsise-00.h
As discussed previously with @schnepe2 and @mschweiger
=> Backport NRLMSISE00 fixes from latest author version

OVP/D3D9Client/CSphereMgr.cpp, OVP/D3D9Client/D3D9Client.cpp, Src/Orbiter/Base.cpp, Src/Orbiter/Baseobj.h, Src/Orbiter/CelSphereAPI.cpp, Src/Orbiter/Planet.cpp, Src/Orbiter/Vessel.cpp, Src/Orbiter/Vessel.h
This commit fixes a couple of memory leaks in the core and D3D9Client.
=> Fix some memory leaks

Src/Orbiter/Body.cpp, Src/Orbiter/Body.h, Src/Orbiter/Celbody.cpp, Src/Orbiter/DlgFocus.cpp, Src/Orbiter/FlightRecorder.cpp, Src/Orbiter/MfdTransfer.cpp, Src/Orbiter/MfdTransfer.h, Src/Orbiter/Planet.cpp, Src/Orbiter/Psys.cpp, Src/Orbiter/Psys.h, Src/Orbiter/Vessel.cpp, Src/Orbiter/Vesselstatus.cpp
This PR does some refactoring of the `Body` class, like using more modern C++ features and simplifying the logic a bit.
=> Body: Some cleanup and refactoring

README.md
=> Add system requirements to readme.md

Sound/XRSound/src/Utils/FileList.cpp, Sound/XRSound/src/Utils/FileList.h, Src/Orbiter/FlightRecorder.cpp, Src/Orbiter/GraphicsAPI.cpp, Src/Orbiter/OptionsPages.cpp, Src/Orbiter/Orbiter.cpp, Src/Orbiter/Planet.cpp, Src/Orbiter/Planet.h, Src/Orbiter/Psys.cpp, Src/Orbiter/Psys.h, Src/Orbiter/TabModule.cpp, Src/Orbiter/TabScenario.cpp, Src/Orbiter/TabScenario.h, Src/Orbiter/TabVideo.cpp, Src/Orbiter/TabVideo.h, Src/Plugin/LaunchpadExtensions/AtmConfig/AtmConfig.cpp, Src/Plugin/ScnEditor/Editor.cpp, Src/Plugin/ScnEditor/Editor.h
This reverts commit acb91358197736b024a1136ada09a7868f8d9e68. *Temporarily*
I have built and tested that Orbiter functions normally.
=> *Temporarily* Revert "Use std::filesystem instead of windows API in Orbiter core"

Orbitersdk/samples/Lua/DeltaGlider/Src/CockpitBrightnessDial.lua, Orbitersdk/samples/Lua/DeltaGlider/Src/CockpitLight.lua, Orbitersdk/samples/Lua/DeltaGlider/Src/CockpitLightSwitch.lua, Orbitersdk/samples/Lua/DeltaGlider/Src/ComponentVessel.lua, Orbitersdk/samples/Lua/DeltaGlider/Src/DGSwitch1.lua, Orbitersdk/samples/Lua/DeltaGlider/Src/Deltaglider.lua, Orbitersdk/samples/Lua/DeltaGlider/Src/InstrumentBrightnessDial.lua, Orbitersdk/samples/Lua/DeltaGlider/Src/InstrumentLight.lua, Orbitersdk/samples/Lua/DeltaGlider/Src/InstrumentLightSwitch.lua, Orbitersdk/samples/Lua/DeltaGlider/Src/LandDockLight.lua, Orbitersdk/samples/Lua/DeltaGlider/Src/LandDockLightSwitch.lua, Orbitersdk/samples/Lua/DeltaGlider/Src/LightCtrlSubsystem.lua, Orbitersdk/samples/Lua/DeltaGlider/Src/MainRetroThrottleLevers.lua, Orbitersdk/samples/Lua/DeltaGlider/Src/NavLight.lua, Orbitersdk/samples/Lua/DeltaGlider/Src/NavLightSwitch.lua, Orbitersdk/samples/Lua/DeltaGlider/Src/StrobeLight.lua, Orbitersdk/samples/Lua/DeltaGlider/Src/StrobeLightSwitch.lua, Orbitersdk/samples/Lua/DeltaGlider/Src/Subsystem.lua, Orbitersdk/samples/Lua/DeltaGlider/Src/meshres_p1.lua, Script/oapi_init.lua, Src/Module/LuaScript/LuaInterpreter/Interpreter.cpp, Src/Module/LuaScript/LuaInterpreter/Interpreter.h, Src/Module/LuaScript/LuaInterpreter/lua_vessel_mtd.cpp
This PR adds support for beacons in the Lua API.
=> [Lua]Add beacon support

Orbitersdk/samples/Lua/DeltaGlider/Src/Airbrake.lua, Orbitersdk/samples/Lua/DeltaGlider/Src/CockpitLight.lua, Orbitersdk/samples/Lua/DeltaGlider/Src/ComponentVessel.lua, Orbitersdk/samples/Lua/DeltaGlider/Src/Deltaglider.lua, Orbitersdk/samples/Lua/DeltaGlider/Src/GearControl.lua, Orbitersdk/samples/Lua/DeltaGlider/Src/HUDControl.lua, Orbitersdk/samples/Lua/DeltaGlider/Src/InstrumentLight.lua
Fixes for the Lua DG SDK :
-mismatch between boolean and integer in key handling
-error when saving scenario with non default instrument light
-error when loading scenario with non default cockpit lights
=> [Lua]Fix Lua DG inputs + errors when loading/saving scenario

OVP/D3D9Client/WindowMgr.cpp, OVP/D3D9Client/WindowMgr.h
- Fixed Ctrl+Shift+Arrow crash
=> Bug fixes and Improvements

Src/Orbiter/Defpanel.cpp
Fixes #464 
I have tested this fix on my own system at 2560x1080 and 1920x1080 (windowed and full-screen).
Someone else should pull, built, and test at a few resolutions too on their own system before merging.
=> fix hover status on default hud

Src/Plugin/ScnEditor/Editor.cpp, Src/Plugin/ScnEditor/Editor.h
=> [ScnEditor]Prevent deletion of the last focusable vessel

Script/Tests/GeneralApiTest.lua, Src/Module/LuaScript/LuaInterpreter/Interpreter.cpp, Src/Module/LuaScript/LuaInterpreter/Interpreter.h
This PR add some planet related oapi functions:
-get_planetobliquity
-get_planettheta
-get_planetobliquitymatrix
-get_planetcurrentrotation
-planet_hasatmosphere
-get_planetatmparams
-get_groundvector
-get_windvector
-get_planetjcoeffcount
-get_planetjcoeff,
=> [Lua]Add some oapiGetPlanetxxx functions

CMakeLists.txt, Doc/Orbiter User Manual/INSTALLATION.tex, Doc/Orbiter User Manual/NEW.tex, README.md, readme.txt
Updated readme files and change log, removed old doc entries, and added readme and license files to release.
=> Readme and changelog update, and release additions

.github/workflows/on-push-linux.yml
Adding a workflow which only triggers in separate branch - `linux` - so that it can be fleshed out in later PRs
=> Adding preliminary Linux workflow

CMakeLists.txt, Src/Module/LuaScript/LuaInterpreter/CMakeLists.txt, Src/Module/LuaScript/LuaInterpreter/lua_xrsound.cpp, Src/Orbiter/CMakeLists.txt, Src/Orbiter/Log.cpp, Src/Orbiter/Log.h, Src/Orbiter/Orbiter.cpp
- Fixed build errors while XRSound is disabled  (not tested with enabled)
- Fixed build errors while documentation build is disabled (not tested while enabled)
- Added logging of loaded modules for better diagnostics
=> Fixed some build errors. Added logging of loaded modules.

Src/Module/LuaScript/LuaInterpreter/Interpreter.cpp
=> [Lua][Fix]Bound checking on keycode arguments

Src/Module/LuaScript/LuaInterpreter/Interpreter.cpp, Src/Module/LuaScript/LuaInterpreter/types.lua
=> [Lua][Doc]Add MATPROP to the Lua types tables

Src/Orbiter/MfdDocking.cpp
This fixes #578 by initialising ndock and taking into account the 3 possibilities when needed :
- no docking port : disable DCK and HUD buttons
- one port : disable DCK button
- otherwise : enable both buttons
=> [DockMFD]Fix crash when the vessel has no docking port

Src/Plugin/LuaMFD/LuaMFD.cpp, Src/Plugin/LuaMFD/LuaMFD.h
This PR converts the LuaMFD to use MFD2 and sketchpad instead of GDI
=> Convert Lua MFD to use sketchpad
