orbitersim/orbiter

Src/Vessel/Dragonfly/CMakeLists.txt, Src/Vessel/ShuttleA/ShuttleA_PL/CMakeLists.txt, Src/Vessel/Solarsail/CMakeLists.txt
There are a few CMakeLists with filenames that don't exactly match the actual files due to case mismatch. On Windows, this doesn't cause any problems since the NTFS is case-insensitive by default, but there's no downside to using exact filenames anyway.
=> Fix case mismatch between filenames in CMakeLists and actual files

.github/workflows/build.yml, .gitignore
Adds a basic CI workflow which builds the project in both x86 and x64 platforms.
Example run: https://github.com/DarkWanderer/orbiter/runs/3196658204?check_suite_focus=true
=> Adding msbuild+CMake+VS2019 CI build

.github/workflows/build.yml, Src/Plugin/ScriptMFD/CMakeLists.txt
* x86 compilation time down by 40-50% 10m -> 5-6m
* x64 compilation time down by 10-50% - 6m -> 3-5m
GitHub agents performance seems to be a bit inconsistent, but the improvement is definitely visible
=> Adding 2-core parallel compilation

CMakeLists.txt, OVP/D3D7Client/CMakeLists.txt, Src/Vessel/DeltaGlider/AAPSubsys.cpp, Src/Vessel/DeltaGlider/DeltaGlider.cpp, Src/Vessel/DeltaGlider/DeltaGlider.h
closes #30 
fixes warning temporarily. But still requires proper code cleanup to remove obsolete DG panel code.
=> 30 warning missing return values

.github/workflows/build.yml
- added 'install' step to pipeline
- added x64 artifact in `main` branch builds with 7 days retention
- switched to explicit invocation of cmake instead of "prefab" action use
- allows to utilize "install" action, better customizability
- lost "problem matchers" - compilation warnings will not be highlighted in CI (will still be logged!)
- switched to `main` from `master`
=> Adding x64 artifact to Actions build

Orbitersdk/include/GraphicsAPI.h, Src/Orbiter/elevmgr.cpp
Clients that manipulate elevation file data in memory (e.g. for
flattening features) for visuals can overload this method in order to
manipulate the terrain collision data in the same way. As soon as the
internal collision tile is loaded in the core, the callback is invoked.
=> elevmgr: added clbkFilterElevation

.github/workflows/build.yml
Check 'install' in addition to 'build' in PRs (to make sure situations like [this](https://github.com/orbitersim/orbiter/runs/3242215571) do not repeat)
=> Check install in CI regardless of branch/bitness

Orbitersdk/samples/AscentMFD/AscentMFD.cpp, Orbitersdk/samples/AscentMFD/AscentMFD.h, Orbitersdk/samples/MFDTemplate/MFDTemplate.cpp, Orbitersdk/samples/MFDTemplate/MFDTemplate.h
Fix MsgProc return type in examples to compile for both x86 and x64 platforms without breaking compatibility.
Mentioned in forum: https://www.orbiter-forum.com/threads/x64-development.40026/post-585380
=> Fix MFDtemplate and AscentMFD for x86 and x64 compatibility

Src/Orbiter/Orbiter.cpp
Fixes usage of g_pane without testing pointer validity.
I found this bug after commenting out the dx7 render system so I could run the server in 64 bit
=> Orbiter server now runs without a 2d graphics surface

.github/workflows/build.yml, CMakeLists.txt, Src/Orbiter/CMakeLists.txt, Tests/CMakeLists.txt, Tests/t_lua_interpreter.cc
First cut of infrastructure for unit tests. GTests proves to be troublesome due to Orbiter's heavy reliance on working directory - TODO a proper framework
=> Unit tests

Doc/.~lock.Orbiter.odt#, Src/Orbiter/CMakeLists.txt, Src/Orbiter/Config.cpp, Src/Orbiter/Config.h, Src/Orbiter/MenuInfoBar.cpp, Src/Orbiter/Orbiter.cpp, Src/Orbiter/Orbiter.h, Src/Orbiter/OrbiterAPI.cpp, Src/Orbiter/TabExtra.cpp, Src/Orbiter/TabModule.cpp, Src/Orbiter/TabModule.h, Src/Orbiter/cmdline.cpp, Src/Orbiter/cmdline.h, Src/Orbiter_ng/Orbiter_ng.cpp
- command line parsing is now done in a seperate singleton class
- a new Config structure (CfgCmdlinePrm) holds the command line parameters
- command line options have precedence over interactive settings in case of conflicts
- additional command line parameters have been added
closes #84
=> 84 add cmdline params

OVP/D3D7Client/Log.h, Src/Orbiter/Log.h
If Orbiter is running under a debugger, a fatal assertion failure will break into the debugger so the developer can snoop around and debug why the assertion failure occurred.
=> Break into debugger on fatal assertion failures if running under debugger

Src/Orbiter/TabModule.cpp
=> #90: fixed uninitialised 'locked' parameter for module list entries.

OVP/D3D7Client/D3D7Client.cpp, OVP/D3D7Client/D3D7Client.h, OVP/D3D7Client/VVessel.cpp, OVP/D3D7Client/VVessel.h, Src/Orbiter/OGraphics.cpp, Src/Orbiter/OGraphics.h, Src/Orbiter/Vessel.cpp, Src/Orbiter/Vobject.h, Src/Orbiter/Vvessel.cpp, Src/Orbiter/Vvessel.h
modified context pointer from UINT to DWORD_PTR to reflect interface change in GraphicsClient.
closes #89
=> #89: Ographics/D3D7Client::clbkVisEvent and VObject::clbkEvent: 

Src/Orbiter/CMakeLists.txt, Src/Orbiter/FlightRecorder.cpp, Src/Orbiter/Log.cpp, Src/Orbiter/Log.h, Src/Orbiter/Orbiter.cpp, Src/Orbiter/Orbiter.h, Src/Orbiter/OrbiterAPI.cpp, Src/Orbiter/console_ng.cpp, Src/Orbiter/console_ng.h
- Console functionality has been moved from Orbiter class to separate orbiter::ConsoleNG class.
- Console now supports 'dlg' command to open dialog windows in the absence of a graphics window.
- The following dialogs can be opened: focus (vessel selection), map, info, tacc (time acceleration), help, record (flight recorder) and function (plugin function list)
- The ExtMFD windows currently don't work in console mode, because of graphics client dependencies
closes #93
=> 93 console mode dialogs

CMakeLists.txt
@DarkWanderer : re #107: Enabling AddressSanitizer failed for me for 32-bit builds, because the name of the asan dlls didn't match (VS 16.10.3). Can you confirm that you have the same problem with the original pull request (#107) and that this edit fixes it?
closes #111
=> #111: asan dll file name fixed for 32-bit builds

Src/Orbiter/CMakeLists.txt, Src/Orbiter/ConsoleManager.cpp, Src/Orbiter/ConsoleManager.h, Src/Orbiter/Orbiter.cpp, Src/Orbiter/console_ng.cpp
- Server version of Orbiter changed to use CONSOLE subsystem
- will now reuse existing console if launched from one
- Allows proper stdout logging for tests
- Allows running/interacting with NG version directly in Visual Studio console
- Downside: flicker of console window on launch (visual only)
=> NG version: allow proper work from interactive console (stdin/stdout)

.github/workflows/build.yml
Adds warnings/errors from MSVC compiler as GitHub annotations (will highlight compilation warnings/errors in PR diff)
=> Add msvc problem matcher

Script/oapi_init.lua, Src/Module/LuaScript/LuaInterpreter/Interpreter.cpp
Loading lua scripts from 'Script/' is not properly defined in stock lua and should explicitly specify the current directory as './Script'
=> Fixes #133  - Fix problem with lua script loading.

Utils/Shipedit/Mesh.cpp
Added missing normalization to vertex normals in Shipedit.
=> Correcting Shipedit calculation of vertex normals

Src/Orbiter/Mesh.cpp, Utils/Shipedit/Mesh.cpp, Utils/meshc/Mesh.cpp
Updated normal calculations on smooth surfaces for meshes with missing normals (shipedit utility and Orbiter core). Bordering triangle contributions are now weighted by the triangle angles at the vertex.
closes #129
=> 129 shipedit normals

.github/workflows/build.yml
This adds support of new D3D9Client build into GitHub Actions build
Example successful build: https://github.com/DarkWanderer/orbiter/actions/runs/1263239535
=> Add DXSDK download into GitHub Actions

OVP/D3D9Client/D3D9Client.cpp, Src/Orbiter/Orbiter.cpp, Src/Orbiter/Pane.cpp, Src/Orbiter/hud.cpp
Fix bug #145 using @spacex15 approach.
Also this was made:
- Add checks to avoid crashes on vessel deleting
- Initialize HUD variables
As EXTERNALGRAPHICS preprocessor variable isn't defined, the change on Src/Orbiter/Orbiter.cpp relies on #else and checking if gclient exists. This work well on headless sessions, but we can save this check (on headless) defining a dedicated variable.
Anyway I think that to do that is out scope of a bug fix, by that I'm using this approach and taking it account for future improves.
=> Fix bug #145 using @spacex15 approach

OVP/D3D9Client/VVessel.cpp, OVP/D3D9Client/samples/GenericCamera/MFD.cpp, Orbitersdk/include/DrawAPI.h, Src/Orbiter/Vessel.cpp, Src/Vessel/Atlantis/Atlantis/AscentAP.cpp, Src/Vessel/DeltaGlider/FuelMfd.cpp, Src/Vessel/DeltaGlider/GearSubsys.cpp, Src/Vessel/DeltaGlider/LightSubsys.cpp, Src/Vessel/DeltaGlider/MomentInd.cpp
- Fix 64bit compiler warnings
- DrawAPI.h Add FMATRIX4 initialization
- Use proper encoding
- Click area only on focused vessels
=> - Fix 64bit compiler warnings

Src/Orbiter/Vessel.cpp
This fixes the ShiftCG() call from an out-of-focus vessel shifting the vc click areas of the in-focus vessel, as reported in https://www.orbiter-forum.com/threads/orbiter-beta-r90-suspected-bug-with-shiftcg-call-and-vc-click-spots.40308/
=> fix ShiftCG() in out-of-focus vessel

Src/Orbiter/State.cpp
Added logic to reset scenario variables to avoid, e.g., the context value being carried over from one scenario run to the next one.
=> Reset scenario variables

Src/Orbiter/Orbiter.cpp, Src/Orbiter/TabVideo.cpp
As discussed in [this thread](https://www.orbiter-forum.com/threads/support-for-plugin-subfolder-dll-search-path.40449/), with the help of @Face-1 I've changed plugin load behavior to:
1. Search for plugins with the pattern `Modules/Plugins/XXX.dll (existing behavior)
2. If not found, search for plugins with the pattern: Modules/Plugins/XXX/XXX.dll
This is useful for cases where plugin A.dll depends on B.dll. Currently orbiter searches for DLLs on the PATH. This means users must install all dependency plugin DLLs to Modules or Modules/Plugins, which adds clutter and potential conflicts between plugins. With this new behavior, a plugin and all its dependencies can be installed to its own subfolder, and will not interfere with the loading of other plugins.
I have only introduce this …
=> Orbiter now searches for graphics client plugins within an optional module subfolder

OVP/D3D7Client/Texture.cpp, OVP/D3D7Client/Texture.h, OVP/D3D7Client/cloudmgr2.cpp, OVP/D3D7Client/surfmgr2.cpp, OVP/D3D7Client/surfmgr2.h, OVP/D3D7Client/tilemgr2.cpp, OVP/D3D7Client/tilemgr2.h, Src/Orbiter/Texture.h, Src/Orbiter/cloudmgr2.cpp, Src/Orbiter/surfmgr2.cpp, Src/Orbiter/surfmgr2.h, Src/Orbiter/tilemgr2.cpp, Src/Orbiter/tilemgr2.h
- inline client now loads planet surface tiles from cache, even if the root is not under the .\Textures directory.
- cleaned up and synchronised some of the equivalent code in OVP\D3D7Client, although this didn't have the same problem.
closes #207
=> 207 loading cache tiles fails

OVP/D3D7Client/D3D7Client.cpp, OVP/D3D7Client/D3D7Client.h, OVP/D3D7Client/D3D7Extra.cpp, OVP/D3D7Client/D3D7Extra.h, Src/Orbiter/OGraphics.cpp, Src/Orbiter/OGraphics.h, Src/Orbiter/Orbiter.cpp, Src/Orbiter/TabExtra.cpp, Src/Orbiter/TabExtra.h
Crash was caused by invalid order of de-registration of Launchpad "Extra" items by D3D7 client. Moved registration calls to "InitModule" and de-registration calls to "ExitModule" to fix this.
Closes #209
=> 209 crash extprm

OVP/D3D7Client/D3D7Client.cpp, Src/Module/LuaScript/LuaInline/LuaInline.cpp, Src/Orbiter/Config.cpp, Src/Orbiter/Config.h, Src/Orbiter/Log.cpp, Src/Orbiter/OGraphics.cpp, Src/Orbiter/OGraphics.h, Src/Orbiter/Orbiter.cpp, Src/Orbiter/Orbiter.h, Src/Orbiter/TabExtra.cpp, Src/Orbiter/Util.cpp, Src/Orbiter/Util.h, Src/Plugin/Rcontrol/Rcontrol.cpp
- Cleaned up module registration and un-registration in Orbiter core.
- Plugin DLLs are responsible for deleting the their module instances after unregistering them with Orbiter.
- Additional log output to diagnose problems with module registration/unregistration.
- Clearer way for plugins to register an unregister items in the Launchpad Extra tab.
- Inline and D3D7 clients now properly unregister and deallocate their resources.
Closes 211
=> 211 module deletion

OVP/D3D7Client/D3D7Client.cpp, Src/Orbiter/Orbiter.cpp, Src/Orbiter/TabVideo.cpp, Src/Orbiter/cryptstring.h.in
D3D7 client closes tile loader thread earlier on simulation shutdown to avoid accessing deleted resources.
Closes #213
=> 213 d3d7 tile loader shutdown

Orbitersdk/include/OrbiterAPI.h, Src/Orbiter/Orbiter.cpp, Src/Orbiter/Orbiter.h
Plugins: orbiter provides default oapi::Module interfaces for any plugins that don't define their own to manage the legacy style callbacks. Locally defined Module instances are freed by Orbiter, DLL-provided ones must be freed by the DLL itself.
Closes #215
=> Default Module interfaces for legacy callbacks

Sound/XRSound/XRSound/assets/XRSound/XRSound.cfg, Sound/XRSound/XRSound/src/XRSoundDLL/VesselXRSoundEngine.cpp, Sound/XRSound/XRSound/src/XRSoundDLL/XRSoundConfigFileParser.cpp, Sound/XRSound/XRSound/src/XRSoundDLL/XRSoundConfigFileParser.h, Sound/XRSound/XRSound/src/XRSoundLib/XRSound.h
User Engine (THGROUP_USER) was missing in XRSound
This pull request adds it
=> Added User Engine Sound to XRSound

Sound/XRSound/XRSound/assets/XRSound/XRSound.cfg, Sound/XRSound/XRSound/src/XRSoundDLL/VesselXRSoundEngine.cpp, Sound/XRSound/XRSound/src/XRSoundDLL/XRSoundConfigFileParser.cpp, Sound/XRSound/XRSound/src/XRSoundDLL/XRSoundConfigFileParser.h, Sound/XRSound/XRSound/src/XRSoundLib/XRSound.h
Reverts orbitersim/orbiter#224
After discussion with Martin and the author of this PR, we decided to revert these changes. See discussion in https://github.com/orbitersim/orbiter/pull/235 for more information.
=> Revert "Added User Engine Sound to XRSound"

Src/Orbiter/OGraphics.cpp, Src/Orbiter/OGraphics.h
This fixes the Shuttle-A issue of dynamic panel elements displayed as white rectangles.
=> #248: Implemented clbkLoadSurface method for inline graphics client.

Src/Orbiter/State.cpp
Fixes compilation error on vs2017, where ```<string>``` must be included for std::string.
Including ```<string.h>``` seems unnecessary.
=> Fixed <string> include in State.cpp for compatibility with vs2017

Orbitersdk/doxygen/CMakeLists.txt, Orbitersdk/include/OrbiterAPI.h, Orbitersdk/include/VesselAPI.h, Src/Orbiter/Body.cpp, Src/Orbiter/Celbody.cpp, Src/Orbiter/FlightRecorder.cpp, Src/Orbiter/Log.h, Src/Orbiter/MenuInfoBar.cpp, Src/Orbiter/SuperVessel.cpp, Src/Orbiter/VBase.cpp, Src/Orbiter/Vessel.cpp, Src/Orbiter/Vessel.h, Src/Orbiter/Vesselstatus.cpp
- User-defined thruster groups (THGROUP_USER+x with x >= 0) should now be fully supported by Vessel class methods and thruster-group related API functions.
- Some cleanup of code in Vessel class; converted thruster and thruster-group related lists to std::vector and std::array
- GetThrusterGroupLevel called with THGROUP_USER should no longer crash (see #235)
Closes #246
=> 246 user defined thruster groups

Src/Plugin/LaunchpadExtensions/AtmConfig/AtmConfig.cpp
=> fix pointer truncation caused by LONG vs LONG_PTR in SetWindowLongPtr call

Src/Vessel/ShuttleA/ShuttleA.cpp, Src/Vessel/ShuttleA/ShuttleA.h
Shuttle-A:
- now deletes sketchpad resources on exit (omission caused log file warnings).
- replaced all remaining GDI drawing calls with Sketchpad versions and removed GDI resources.
Fixes #259.
=> 259 shuttlea sketchpad resources

OVP/D3D7Client/tilelabel.cpp, OVP/D3D9Client/TileLabel.cpp, Src/Orbiter/tilelabel.cpp
An exception occurs if a planet's label layer contains label types not listed in its legend file.
The reason is the used of an uninitialised variable ('active').
Solution: All graphics clients: TileLabel::Render: initialised 'active' flag to false before scanning label legend.
Closes #260.
=> #260: Fix exception on surface label types not in legend

Src/Orbiter/CMakeLists.txt
Enforce sequential build of Orbiter inline and server. Delete Orbiter.lib and Orbiter.exp after first pass.
Closes #269 .
=> #269: Address build failures on dual inline graphics/server builds

OVP/D3D9Client/Surfmgr2.cpp
D3D9Client: apply tgt_res to the rescale and offset values of elevation mod tiles.
This should fix the elevation artefacts at Edwards and Mojave spaceport (Antelope Valley texture pack)
=> #275: D3D9Client: Fix elevation artefacts for elev_mod tiles

OVP/D3D7Client/VideoTab.cpp, Src/Orbiter/TabVideo.cpp
Fix switching between graphics clients in video tab.
- Update video tab dialog elements to reflect selected client.
- Rescan video devices on switch.
Closes #228.
=> 228 video tab update on client change

OVP/D3D7Client/Scene.cpp, OVP/D3D7Client/Scene.h, OVP/D3D7Client/VObject.cpp, OVP/D3D7Client/VObject.h, OVP/D3D7Client/VPlanet.cpp, OVP/D3D7Client/VPlanet.h, OVP/D3D7Client/VVessel.cpp, OVP/D3D7Client/VVessel.h, OVP/D3D9Client/D3D9Client.cpp, OVP/D3D9Client/OapiExtension.cpp, OVP/D3D9Client/OapiExtension.h, OVP/D3D9Client/Scene.cpp, OVP/D3D9Client/VVessel.cpp, Orbitersdk/include/GraphicsAPI.h, Src/Orbiter/Config.cpp, Src/Orbiter/Config.h, Src/Orbiter/DlgVishelper.cpp, Src/Orbiter/Scene.cpp, Src/Orbiter/Scene.h, Src/Orbiter/VBase.cpp, Src/Orbiter/VBase.h, Src/Orbiter/VPlanet.cpp, Src/Orbiter/VPlanet.h, Src/Orbiter/Vobject.cpp, Src/Orbiter/Vobject.h, Src/Orbiter/Vvessel.cpp, Src/Orbiter/Vvessel.h
- Allows access to the vessel force vector and object frame axis display dialog options via GetConfigParam
- Implements force vector and frame axis display in D3D7 client
- Updates D3D9Client to retrieve the display options from the default GraphicsClient interface. Removes the workaround of hooking into the visual helpers dialog message loop from OapiExtension.
- General cleanup of force vector and object axis rendering code in inline client.
- Still to do: vector labels in D3D7 client (deferred to a separate branch implementing improved text label rendering).
Closes #283.
=> API: Expose force vector and object axis display options

Src/Orbiter/DlgVishelper.cpp
...to intptr_t. The wrong type lead to exception in _findnext(...) call on x64 builds.
=> fixed type for FindFirst / FindNext

Src/Orbiter/Config.cpp, Src/Orbiter/Config.h, Src/Orbiter/Orbiter.cpp, Src/Orbiter/Orbiter.h, Src/Orbiter/TabModule.cpp, Src/Orbiter/TabVideo.cpp
- Rearranged module load sequence to an order that doesn't appear to exhibit the D3D7 client hangups, although the actual cause of the problem isn't really addressed.
- Cleaned up some of the code for manipulating the active module list in Config.
Closes #297.
=> 297 d3d7client hangup on launch

OVP/D3D7Client/CSphereMgr.cpp, Src/Orbiter/CSphereMgr.cpp
Inline and D3D7 clients: re-designed render stage pipeline for combining celestial background and starfield images.
Closes #301.
=> Fix celestial background intensity render bug (inline + D3D7 clients)

OVP/D3D7Client/CelSphere.cpp, OVP/D3D9Client/CelSphere.cpp, Src/Orbiter/CelSphere.cpp
#311: All clients: If gridlabel.dds texture is not found, an error message is written to the log, and grid labels are not displayed. D3D9 client no longer crashes.
=> Deal with missing gridlabel.dds texture file

OVP/D3D9Client/TileLabel.cpp
the fix for #260 was lost. Re-applied.
Regression was found and reported here: https://www.orbiter-forum.com/threads/d3d9client-development.16787/post-604929
=> Fixed a regression,

Src/Orbiter/TabScenario.cpp
Removed 256 char line limit when saving current scenario (a.k.a."Save current ..." button), which if exceeded would cause scenario copy to be terminated, resulting in an incomplete scenario.
=> Save current scenario line length fix

Src/Orbiter/OrbiterAPI.cpp, Src/Orbiter/ZTreeMgr.h, Src/Orbiter/elevmgr.h, Src/Orbitersdk/Orbitersdk.cpp, Utils/Pltex/Pltex.cpp, Utils/scramble/scramble.cpp
This is a first batch of clean-up patches discussed in #338 to enable C++20 standard conformance.
The purpose of these patches is to enable C++20 conformance of the existing code with minimal changes, so that further clean-up can be done as the next step.
The patches were purposely made very small and easy to review/accept, and will also aid any further bisects if necessary to find bugs.
=> Clean-up patches

Src/Orbiter/OrbiterAPI.cpp, Src/Orbitersdk/Orbitersdk.cpp
This partially reverts commit 055f9666ff6d6803ccf75ffbb5e2fa8eb10a1987, which broke some of the precompiled binaries depending on Date2Int().
=> Fix Date2Int() signature

OVP/D3D7Client/Camera.cpp, OVP/D3D7Client/VObject.cpp, OVP/D3D7Client/VStar.cpp, OVP/D3D9Client/CelSphere.cpp, OVP/D3D9Client/Scene.cpp, OVP/D3D9Client/VStar.cpp, OVP/D3D9Client/samples/DrawOrbits/Draw.cpp, Src/Orbiter/Baseobj.cpp, Src/Orbiter/Camera.cpp, Src/Orbiter/Element.cpp, Src/Orbiter/MfdDocking.cpp, Src/Orbiter/MfdLanding.cpp, Src/Orbiter/MfdMap_old.cpp, Src/Orbiter/MfdTransfer.cpp, Src/Orbiter/VectorMap.cpp, Src/Orbiter/Vessel.cpp, Src/Orbiter/Vobject.cpp, Src/Orbiter/Vstar.cpp, Src/Orbiter/hud.cpp, Src/Plugin/ScnEditor/Editor.cpp
This PR replaces calls to MSVC specific _hypot with standard std::hypot function
=> Use std::hypot instead of _hypot

Src/Orbiter/Launchpad.h, Src/Orbiter/Log.cpp, Src/Orbiter/Mfd.cpp, Src/Orbiter/MfdAlign.cpp, Src/Orbiter/MfdComms.cpp, Src/Orbiter/MfdDocking.cpp, Src/Orbiter/MfdHsi.cpp, Src/Orbiter/MfdLanding.cpp, Src/Orbiter/MfdMap.cpp, Src/Orbiter/MfdMap_old.cpp, Src/Orbiter/MfdOrbit.cpp, Src/Orbiter/MfdSurface.cpp, Src/Orbiter/MfdSync.cpp, Src/Orbiter/MfdTransfer.cpp, Src/Orbiter/Orbiter.cpp, Src/Orbiter/Pane.cpp, Src/Orbiter/Vessel.cpp
Key consumers should consume OAPI_KEY codes and not DirectInput keycodes.
This limits the coupling between the internal MFDs and DirectInput
=> Use OAPI_KEY_* instead of DIK_*

Src/Orbiter/D3d7enum.cpp, Src/Orbiter/DlgCapture.cpp, Src/Orbiter/FlightRecorder.cpp, Src/Orbiter/Mfd.cpp, Src/Orbiter/MfdLanding.cpp, Src/Orbiter/OGraphics.cpp, Src/Orbiter/OptionsPages.cpp, Src/Orbiter/Vessel.cpp, Src/Orbiter/console_ng.cpp, Src/Orbiter/hud.cpp
This PR replaces MSVC specific _itoa with standard sprintf.
Rational for not using std::to_string or equivalent : _itoa is usually used in C strings heavy contexts, mixing C++ strings in there would only clutter the code for no good reason. Feel free to disagree, I can change my mind if necessary.
Integer formating is size limited so I used snprintf only where a buffer overflow was possible.
Code in OVP/D3D* was not modified since it will obviously needs MSVC to compile anyway.
=> Replace non standard _itoa

Orbitersdk/include/DrawAPI.h, Orbitersdk/include/VesselAPI.h
This keeps Windows min/max macros from kicking in and causing errors.
=> Wrap std::min/max calls in parens

OVP/D3D7Client/D3D7Enum.cpp, OVP/D3D7Client/VideoTab.cpp, OVP/D3D9Client/VideoTab.cpp, Src/Orbiter/Mfd.cpp
Second round to replace _itoa calls in OVP.
I took this opportunity to work around a warning introduced earlier in the 32bit build.
=> Replace itoa with std::to_string

CMakeLists.txt, OVP/D3D9Client/D3D9Util.cpp, OVP/D3D9Client/D3D9Util.h, OVP/D3D9Client/Mesh.cpp, OVP/D3D9Client/TileMgr.cpp, OVP/D3D9Client/samples/DrawOrbits/Tools.cpp, Src/Orbiter/CelSphere.cpp
- Removed 'register' keyword.
- fixed link warnings.
- Replaced prt() function with '&' macro.
- Set default standard to C++17
=> Minor code fixes

Sound/XRSound/src/Utils/FileList.cpp, Sound/XRSound/src/Utils/FileList.h, Src/Orbiter/FlightRecorder.cpp, Src/Orbiter/GraphicsAPI.cpp, Src/Orbiter/OptionsPages.cpp, Src/Orbiter/Orbiter.cpp, Src/Orbiter/Planet.cpp, Src/Orbiter/Planet.h, Src/Orbiter/Psys.cpp, Src/Orbiter/Psys.h, Src/Orbiter/TabModule.cpp, Src/Orbiter/TabScenario.cpp, Src/Orbiter/TabScenario.h, Src/Orbiter/TabVideo.cpp, Src/Orbiter/TabVideo.h, Src/Plugin/LaunchpadExtensions/AtmConfig/AtmConfig.cpp, Src/Plugin/ScnEditor/Editor.cpp, Src/Plugin/ScnEditor/Editor.h
This PR mainly replaces the findfirst/findnext windows API with std::filesystem iterators.
We could go further with introducing fs::path in more places but it will need to wait since it'll likely break the ABI.
Impacts where something may have been broken :
- scenario editor
- atmosphere modules enumeration/configuration
- video module enumeration
- module enumeration
- scenario enumeration
- Quicksave folder cleanup from the launchpad
- markers/features enumeration
- bases enumeration
- flight recorder (directory cleanup when overwriting a record)
One thing I've not been able to test confidently is the PlanetarySystem::ScanLabelLists function.
=> Use std::filesystem instead of windows API in Orbiter core

Src/Orbiter/OptionsPages.cpp, Src/Orbiter/OptionsPages.h
Options in Visual settings and Physics settings pages were not being immediately saved, which caused any changes to be lost when changing to another options page. This PR should fix that issue, and also adds logic to disable the Planet night light level text box when Planet night lights are disabled, and also disable the terrain interpolation combo box when Surface elevation is disabled.
BEWARE: I'm using VS2017 and cannot compile the latest version of the code, so this was only tested in a 1 year+ old code version. I think it should work fine and not need any further work but still, it should be well tested in the latest code before merging.
=> Fix Option Save

OVP/D3D9Client/D3D9Client.cpp
Fixed (hopefully) d3d9 device creation on wine. Issue #420
=> Fixed (hopefully) d3d9 device creation on wine.

.github/workflows/build.yml, Src/Orbiter/Planet.cpp, Src/Orbiter/Psys.cpp
This PR fixes the build issues when compiling with VS2022, it also adds CI jobs to detect potential future failures.
The artifacts for the VS2022 builds are not saved for now.
=> Add support for VS2022

Script/strict.lua, Src/Module/LuaScript/LuaInterpreter/Interpreter.cpp, Src/Module/LuaScript/LuaInterpreter/Interpreter.h
This PR adds support for the oapiOpenInputBoxEx function in ScriptVessels/ScriptMFDs
Differences with the C++ version :
-callbacks only take 2 arguments (str and usrdata) since the first "void *id" is useless
-cancel callback does not need to return a bool since it's ignored by the core anyway
=> [Lua]Add support for oapiOpenInputBoxEx

Orbitersdk/samples/Lua/Atlantis/Src/Atlantis.lua, Orbitersdk/samples/Lua/Atlantis/Src/CameraMFD.lua, Src/Module/LuaScript/LuaInterpreter/CMakeLists.txt, Src/Module/LuaScript/LuaInterpreter/Interpreter.cpp, Src/Module/LuaScript/LuaInterpreter/Interpreter.h, Src/Module/LuaScript/LuaInterpreter/lua_vessel_mtd.cpp, Src/Module/LuaScript/LuaInterpreter/types.lua
This PR adds support for D3D9 custom cameras.
The gcCore API is hidden behind oapi calls to make usage straightforward :
- oapi.setup_customcamera
- oapi.delete_customcamera
- oapi.customcamera_overlay
- oapi.customcamera_onoff
The manual is updated and an example MFD has been added to the Lua Atlantis vessel (basically a simplified port of the GenericCamera from D3D9Client)
Along with this, some new API has been added to support the GenericCamera port :
- oapi.clear_surface
- skp.copy_rect
- skp.stretch_rect
- skp.rotate_rect
- skp.quick_pen
- skp.quick_brush
- skp.get_surface
- skp.set_brightness
- skp.set_renderparam
- skp.set_worldtransform2d
=> [Lua]Add support for custom cameras and related sketchpad APIs

.github/workflows/nightly.yml
Purpose: check that it is worth running another instance of nightly build
=> Perform pre-check before running nightly

OVP/D3D9Client/AtmoControls.cpp, OVP/D3D9Client/D3D9TextMgr.cpp, OVP/D3D9Client/Mesh.cpp, OVP/D3D9Client/VPlanet.cpp, OVP/D3D9Client/VPlanetAtmo.cpp
- Fixed Neptune lighting issue. Further testing needed.
- Disabled MSAA when using mesh flag 0x20 to avoid edge glow.
- Enabled full range of charters for text output.
=> Finishing touches

Orbitersdk/samples/Lua/Atlantis/Src/APMFD.lua, Src/Module/LuaScript/LuaInterpreter/CMakeLists.txt, Src/Module/LuaScript/LuaInterpreter/Interpreter.cpp, Src/Module/LuaScript/LuaInterpreter/Interpreter.h, Src/Module/LuaScript/LuaInterpreter/config.ld, Src/Module/LuaScript/LuaInterpreter/lua_xrsound.cpp, Src/Module/LuaScript/LuaInterpreter/types.lua
This PR adds support for XRSound in Lua scripts with a new 'xrsound' module/class.
Example usage:
```
function clbk_postcreation()
snd = xrsound.create_instance(vi)
snd:load_wav(1, "XRSound/Default/On.wav", PlaybackType.InternalOnly)
snd:load_wav(2, "XRSound/Default/Off.wav", PlaybackType.InternalOnly)
end
function clbk_consumebufferedkey(key, down, kstate)
if not down then -- only process keydown events
return false
end
if oapi.keydown(kstate, OAPI_KEY.A) then
snd:play_wav(1)
return true
end
if oapi.keydown(kstate, OAPI_KEY.B) then
snd:play_wav(2)
return true
end
return false
end
```
Edit: test binaries: [lua_xrsound_x86_release.zip](https://github.com/user-attachments/files/15937390/lua_xrsound_x86_release.zip)
Manual: [Manual.zip](https://github.com/user-attachments/files/15937386/Manua …
=> [Lua]Add support for XRSound

OVP/D3D9Client/D3D9Client.cpp, OVP/D3D9Client/D3D9Client.h, OVP/D3D9Client/gcConst.cpp, OVP/D3D9Client/gcCore.cpp
@jarmonik can confirm but it looks like there's been some kind of naming confusion between clbkSetMaterialEx and clbkSetMeshMaterialEx.
oapiSetMaterialEx in the core calls clbkSetMeshMaterialEx in the GC.
The D3D9Client implements a clbkSetMaterialEx method which is used by the gcCore API but it will not match when calling oapiSetMaterialEx and the default implementation will be used (i.e. "return 2;").
I modified the D3D9Client to implement the correct naming but it could also be done by changing the GC interface in the core.
Don't know what's best between naming consistency in the core (clbkSetMeshMaterial, clbkMeshMaterial and clbkMeshMaterialEx also exist) or the GC ; tell me if you think it should be done the other way around.
=> [DX9]Fix oapiSetMaterialEx

Src/Vessel/Solarsail/SolarSail.h, Src/Vessel/Solarsail/Solarsail.cpp
This PR fixes the SolarSail vessel. It was using the old oapiMeshGroup API to patch vertex positions so that it only worked with MOGE.
Change it to use oapiEditMeshGroup instead.
=> Fix SolarSail dynamic geometry with DX9

Src/Orbiter/Orbiter.cpp
This PR patches the bug where the mouse could disappear when alt tabbing from the game, this was an almost game-breaking bug where you would have to restart your entire sim in order to fix the bug. The mouse now has a global hide counter to check for if it is already hidden, and prevents it from being hidden twice, this makes it so it can never be permanently hidden, as ShowCursor(true) only increments the counter by 1, whereas before it'd get stuck below 0 and therefore stay permanently hidden. 
After patching the alt-tab bug, I noticed a bug in NASSP where when moving and scrolling the mouse, it would activate unintended buttons when trying to change the FOV. Rather than changing the FOV it would perform the "right click" action on any button while scrolling. I do not believe this is …
=> fix: rotationmode now takes mouse priority over panel buttons + alt-tab mouse disappearing fix

Src/Module/LuaScript/LuaInterpreter/CMakeLists.txt, Src/Module/LuaScript/LuaInterpreter/Interpreter.cpp, Src/Module/LuaScript/LuaInterpreter/lua_vessel_mtd.cpp
The Lua documentation does not need LaTeX and all tools necessary to produce it are in the repo ; we might as well generate it automatically.
The orbiter_lua.chm file is installed in Orbitersdk/doc.
=> [Lua]Generate doc by default

Orbitersdk/samples/Lua/Atlantis/Src/Atlantis.lua, Src/Module/LuaScript/LuaInterpreter/lua_vessel_mtd.cpp
This PR fixes the bug reported [here](https://www.orbiter-forum.com/threads/what-does-vessel-get_rawstatus-1-return.41962/).
=> [Lua]Fix get_rawstatus

Src/Vessel/ScriptVessel/ScriptVessel.cpp
This fixes the bug reported [here](https://www.orbiter-forum.com/threads/invisible-hud.41956/).
The default VESSEL3::clbkDrawHUD method was only called if a callback was defined in the vessel script.
I checked for similar issues with other callbacks but it was the only instance.
=> [Lua]Fix HUD not showing if clbk_drawHUD is not defined

OVP/D3D9Client/D3D9Util.cpp, Src/Module/LuaScript/LuaInterpreter/CMakeLists.txt, Src/Vessel/ScriptVessel/ScriptVessel.cpp
Fix lame typo in ScriptVessel.cpp preventing clbk_visualdestroyed from being called.
=> [Lua]Fix clbk_visualdestroyed not being called

OVP/D3D9Client/D3D9Util.cpp, Src/Module/LuaScript/LuaInterpreter/CMakeLists.txt, Src/Orbiter/Vessel.cpp, Src/Orbiter/Vessel.h
This PR fixes the issue #512
The "permanent" level of thrust was not clamped when using the IncThrusterLevel API.
=> Fix unchecked thruster level

Src/Module/LuaScript/LuaInline/LuaInline.cpp, Src/Module/LuaScript/LuaInline/LuaInline.h, Src/Module/LuaScript/LuaInterpreter/Interpreter.cpp, Src/Module/LuaScript/LuaInterpreter/Interpreter.h, Src/Module/LuaScript/LuaInterpreter/lua_vessel_mtd.cpp, Src/Module/LuaScript/LuaInterpreter/lua_xrsound.cpp, Src/Vessel/DeltaGlider/DGLua.cpp, Src/Vessel/HST/HST_Lua.cpp, Src/Vessel/Quadcopter/QuadcopterLua.cpp, Src/Vessel/ShuttleA/ShuttleALua.cpp, Src/Vessel/Solarsail/SailLua.cpp
This PR adds checks on the "self" parameter when a Lua command executes a virtual function on vessel objects.
Prior to this, there were opportunities for CTD when the user forgot to use the ":" notation when calling a vessel method.
A proper Lua error is now propagated when we try to convert a non vessel object to a VESSEL *.
Orbiter vessels providing Lua bindings have also been updated to check for proper type before casting userdata to VESSEL objects.
Note : luaL_checkudata is not used in the interpreter because we cannot know what type of vessel is to be expected. Instead a set of VESSEL objects is maintained and checked against to test if a userdata is associated with a known vessel.
This method is robust to vessel deletion. If for example you do
v=vessel.get_interface("ISS")
then …
=> [Lua]Harden vessel dereferencing

Src/Module/LuaScript/LuaInterpreter/lua_vessel_mtd.cpp
Some functions may fail (e.g. adding particle streams when particles are disabled) and return a userdata containing a NULL pointer.
Since the userdata is opaque, there is no way to know that the function failed from a calling script.
This PR prevents returning such userdata and returns nil instead so that scripts can handle the failure gracefully.
=> [Lua]Return nil instead of bogus userdata when functions fail

OVP/D3D9Client/samples/DrawOrbits/Tools.cpp
Fix for bad degree char in DrawOrbits, as suggested in #510
=> DrawOrbits bad degree char

Extern/Lua/CMakeLists.txt, Src/Module/LuaScript/LuaInterpreter/CMakeLists.txt
Allows CMake configure to complete with
```
ORBITER_BUILD_D3D9CLIENT=OFF
ORBITER_BUILD_XRSOUND=OFF
```
Note that LuaInterpreter does not build correctly without XRSound for now
=> Fixed cmake configure with default options turned off

Doc/Orbiter Developer Manual/SCENARIO.tex, OVP/D3D9Client/D3D9Client.cpp, OVP/D3D9Client/D3D9Client.h, Orbitersdk/include/GraphicsAPI.h, Src/Orbiter/Orbiter.cpp, Src/Orbiter/State.cpp, Src/Orbiter/State.h, Src/Orbiter/Util.cpp, Src/Orbiter/Util.h
~~This PR should probably wait for after the 2024 release.~~
This adds support for custom load screens via a new scenario parameter "SplashScreen" in the ENVIRONMENT section :
```
BEGIN_ENVIRONMENT
System Sol
Date MJD 51982.0975169074
SplashScreen lime Images/myawesomelogo.jpg
END_ENVIRONMENT
```
The first parameter is a color ~~in 0xbbggrr format~~ described as a [CSS color](https://drafts.csswg.org/css-color/#named-colors) (either in #hex or as a color name), followed by the image filename to be shown on the splashscreen.
The color name is case insensitive, I tested with filenames containing spaces and it works OK.
The image is scaled with the same logic as the embedded Orbiter logo.
Since I was messing with State.h, I took the opportunity to replace the error prone char arrays with …
=> Splashscreen customization

OVP/D3D9Client/D3D9Pad2.cpp, OVP/D3D9Client/D3D9TextMgr.cpp
This is a tentative fix for #558
@jarmonik : can you have a look at this ? Looks like the color format is wrong for TextW. I don't know if it's configurable somewhere so I had to invert the red and blue channels.
=> [D3D][Fix]Honor text alignment in TextW

Src/Orbiter/Di7frame.cpp
Several people have described missing devices in the joystick configuration window.
Without this fix, my XBOX controller is not detected either.
=> [Fix][Joystick]Modify device enumeration

Src/Module/LuaScript/LuaInterpreter/Interpreter.cpp
=> [Lua][Fix]Return 2 values on call to oapi_get_windvector

OVP/D3D9Client/Surfmgr2.cpp
Whenever a surface tile is loaded, it first checks if the surface markers setting is enabled before creating the labels for the tile, meaning that if the setting is enabled during a session, previously loaded tiles don't show their labels, as they haven't been created. This PR removes the check in order to always create the labels for a tile, regardless of the setting. This doesn't affect the actual display of the labels, which still honors the setting.
=> Always create surface tile labels on initial load, regardless of launchpad config

.github/workflows/reusable-build.yml
=> Move to windows-2022 runner for reusable-build
